### ISSUE TITLE
Cannot View messages being sent to IOT Hub

### ISSUE THREAD

**Issue by Y07yoyo** [ebertrams/iotedge-iva-nano#28]
Hi,

I have followed the instructions on this github and created the device using IOT Central. 
I would like to monitor the messages being sent to see what the data is. I have created an IOT Edge device on IOT Hub with the same connection parameters as the one from IOT Central. I have clicked on monitor built-in events but there are no messages being sent.

Is thisa feature that is not available? I do see a line in the deployment.json that specifically states to route messages from IOTCentralBridge to Upstream (FiltertoIotHub)?

Thanks

**Comment by Y07yoyo** [comment]
To summarize, I would like to be able to change models and cameras etc from the IOT Central, but also view the messages being sent to IOT Hub to verify the messages and check the data being sent.
I can modify the config.yaml to either handle the device with the Hub or the Central. But I cannot do both. Is this possible?

Thanks

**Comment by emmanuel-bv** [comment]
This is unfortunately not possible today because you do not have access to the IoT Hub that IoT Central manages for you. The VS Code team is however working on a way to monitor your messages sent to Central.
