### ISSUE TITLE
Whitespace character breaks parsing of classifier labels in IoTCentralBridge

### ISSUE THREAD

**Issue by toolboc** [ebertrams/iotedge-iva-nano#3]
I noticed that when using a custom vision ai model, the output of deepstream seems to be appending a "\r" to the secondary classifier name.  This has a side effect in the IoTCentralBridge which causes it not to send telemetry for the secondary classifier.
 
![image](https://user-images.githubusercontent.com/2018336/72945183-bad5da80-3d40-11ea-8349-0b7a2a57debb.png)

It seems the whitespace character is being introduced through labels.txt in /data/misc/storage/ONNXSetup/detector

![image](https://user-images.githubusercontent.com/2018336/72945198-cb865080-3d40-11ea-8857-19ac82de84c9.png)

Notice that the primary detector is not affected.

![image](https://user-images.githubusercontent.com/2018336/72945218-d8a33f80-3d40-11ea-8267-09397b5ae1c8.png)

Converting labels.txt to use Unix line-endings with dos2unix and restarting the deepstream container alleviates the issue but it will return if the IoTCentralBridge us restarted as it will re-pull the custom vision model which comes down with Windows line-endings.

**Comment by emmanuel-bv** [comment]
Fixed by Scott in one of the latest IoTCentralBridge version, which trims out end of line characters
