### ISSUE TITLE
Count Per Video Stream

### ISSUE THREAD

**Issue by Y07yoyo** [ebertrams/iotedge-iva-nano#30]
Hi,

Is it possible to modify this program to have a separate dashboard display for count for each video stream? (Ie: Count for Cam01, Count for Cam02, count for Cam03, etc?)

Kind Regards,

**Comment by emmanuel-bv** [comment]
Yes, however you would need to modify the contract between the edge device and IoT central (e.g. the this DCM file https://github.com/ebertrams/iotedge-iva-nano/blob/master/NVIDIAJetsonNanoDcm.json) and the code of hte module collecting and sending info to IoT Central from IoT Edge. Today it only sends two counts which are named "Primary Detection Count" and "Primary Detection Count", you will have add counts on a per camera basis.

**Comment by Y07yoyo** [comment]
Hi,
Thanks for the help. I have tried to create a new Telemetry to add the two Primary and Secondary counts to display the total detections. The message is being sent to IOT Central correctly:

In iotCentral.ts I have added the following where the other telemetries are defined:
Zone01Count: 'tlZone01Count',

And then where the Primary and Seconday detections get sent I have added this:
if (zone01Count > 0) {
            await this.sendMeasurement({
                [ModuleInfoFieldIds.Telemetry.Zone01Count]: zone01Count
            });

The iotedge logs for IotCentralBridge are as follows:
[01:52:10 GMT+0000], [log,[IoTCentralService, info]] data: sendEvent: {
    "tlPrimaryDetectionCount": 4
}
[01:52:10 GMT+0000], [log,[IoTCentralService, info]] data: sendEvent: {
    "tlSecondaryDetectionCount": 3
}
[01:52:10 GMT+0000], [log,[IoTCentralService, info]] data: sendEvent: {
    "tlZone01Count": 7
}

I have imported the capability DCM from the github and added a new capability for Zone01Count as an integer. But when I am displaying the data nothing shows up on Zone 01 Count.
![definingzone1count](https://user-images.githubusercontent.com/40599534/81029455-622de600-8ec8-11ea-8d4d-872abd25141f.JPG)

 I was wondering if you could give me some insight into what I must be doing wrong?
![Zone1Count](https://user-images.githubusercontent.com/40599534/81029418-30b51a80-8ec8-11ea-9ac3-5423b1354014.JPG)

**Comment by Y07yoyo** [comment]
It does however show in the analytics tab in IOT Central:
![analytics](https://user-images.githubusercontent.com/40599534/81032754-5c3e0200-8ed4-11ea-8cb7-faa4940dbd8b.JPG)
