### ISSUE TITLE
export data from iot central app to blob storage

### ISSUE THREAD

**Issue by Y07yoyo** [ebertrams/iotedge-iva-nano#32]
Hi,

I am trying to export the data coming from the iot central application to a blob storage. I have set everything up like the docs but when I go to view the telemetry data in blob storage I get the following:

`{"EnqueuedTimeUtc":"2020-06-18T06:04:34.5250000Z","Properties":{},"SystemProperties":{"connectionDeviceId":"NanoTest01","connectionModuleId":"IoTCentralBridge","connectionAuthMethod":"{\"scope\":\"module\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}","connectionDeviceGenerationId":"637269117958401923","enqueuedTime":"2020-06-18T06:04:34.5250000Z"},"Body":"eyJ0bFN5c3RlbUhlYXJ0YmVhdCI6MX0="}`

Do you have any insight as to why the "Body" field is displaying this string instead of all the telemetry data?

Thanks

**Comment by emmanuel-bv** [comment]
Hi @Y07yoyo , could you please give the exact doc articles that you follow so that we can reproduce on our end? Thanks!

**Comment by Y07yoyo** [comment]
Hi @ebertrams, Thank you for your message. I have followed the following article: https://docs.microsoft.com/en-us/azure/iot-central/core/howto-export-data
I created just the storage account not the event hub or service hub.

Thank you

**Comment by Y07yoyo** [comment]
Hi @ebertrams, were you able to isolate this issue?

Kind Regards,

Yusuf

**Comment by emmanuel-bv** [comment]
Hi Yusef, sorry for the delay. @sseiber do you have some guidelines for Yusuf to export data from IoT Central to Blob storage?

**Comment by sseiber** [comment]
@Y07yoyo is it possible you are sending telemetry with that content (e.g. "eyJ0bFN5c3RlbUhlYXJ0YmVhdCI6MX0=") ? Can you verify this with logging or debugging?

**Comment by Y07yoyo** [comment]
Hi @sseiber and @ebertrams,
I have attached the logs of the IoTCentralBridge Module which is sending to IoT Central. As you can see the telemetry is just counts and normal as per the example of this project.
I have also attached the json of the blobl storage for one file in txt.

[IoTCentralBridge_log.txt](https://github.com/ebertrams/iotedge-iva-nano/files/4899735/IoTCentralBridge_log.txt)
[010501.txt](https://github.com/ebertrams/iotedge-iva-nano/files/4899748/010501.txt)

Is there any more information I can provide you with to help identify my issue?

Thanks for the help

Kind Regards,

Yusuf

**Comment by sseiber** [comment]
(Sorry I'm not the expert in how we export to Blob but I did investigate a bit).

It looks like the values in Blob are base64 encoded. For instance if I base64 **decode** one of the values in your log I get this:
```
{"tlInference":{"cameraIDInt":"4","entryCount":"1","exitCount":"3"}}
```

I found [this discussion](https://github.com/MicrosoftDocs/azure-docs/issues/47684) which says you need to set the content type of your payloads to 'application/json' and 'utf-8'

**Comment by Y07yoyo** [comment]
Hi @sseiber Thank you for that. I have decoded one as well and it appears to get the right values.

The discussion says that the message going to iot central need to have the following:

`message.contentEncoding = "utf-8";
message.contentType = "application/json";
`
@ebertrams in the iotCentral.ts module, function sendMeasurement, do I add the settings there? Like shown below:

        try {
            const iotcMessage = new Message(JSON.stringify(data));

            iotcMessage.contentEncoding = "utf-8";
            
            iotcMessage.contentType = "application/json";

            await this.iotcClient.sendEvent(iotcMessage);

            if (_get(process.env, 'DEBUG_TELEMETRY') === '1') {
                this.logger.log(['IoTCentralService', 'info'], `sendEvent: ${JSON.stringify(data, null, 4)}`);
            }

            for (const key in data) {
                if (!data.hasOwnProperty(key)) {
                    continue;
                }

                this.measurementsSentInternal++;
            }
        }
        catch (ex) {
            this.logger.log(['IoTCentralService', 'error'], `sendMeasurement: ${ex.message}`);
        }
    }

![SendMessage](https://user-images.githubusercontent.com/40599534/87098470-b4093880-c28a-11ea-98a0-89cf9838d747.PNG)

**Comment by Y07yoyo** [comment]
Hi @ebertrams and @sseiber 

I can confirm modifying the sendMeasurement function in the iotcentral.ts file to be :

```
@bind
    public async sendMeasurement(data: any): Promise<void> {
        if (!data || !this.iotcClientConnected) {
            return;
        }

        try {
            const iotcMessage = new Message(JSON.stringify(data));

            iotcMessage.contentEncoding = 'utf-8';
            iotcMessage.contentType = 'application/json';

            await this.iotcClient.sendEvent(iotcMessage);

            if (_get(process.env, 'DEBUG_TELEMETRY') === '1') {
                this.logger.log(['IoTCentralService', 'info'], `sendEvent: ${JSON.stringify(data, null, 4)}`);
            }

            for (const key in data) {
                if (!data.hasOwnProperty(key)) {
                    continue;
                }

                this.measurementsSentInternal++;
            }
        }
        catch (ex) {
            this.logger.log(['IoTCentralService', 'error'], `sendMeasurement: ${ex.message}`);
        }
    }
```
has got me the correct results and now the body field is displaying the telemetry data. Attached is the blob file to verify:
[03103.txt](https://github.com/ebertrams/iotedge-iva-nano/files/4900289/03103.txt)

Thank you!

**Comment by emmanuel-bv** [comment]
great that you re unblocked! Please send me a PR if you would like me to merge this is into this repo. Thanks
