### ISSUE TITLE
IoTCentral module needs restarting everytime iotedge is restarted

### ISSUE THREAD

**Issue by Y07yoyo** [ebertrams/iotedge-iva-nano#34]
Hi @ebertrams,

I am finding another issue when I restart IoTEdge:
`sudo systemctl restart iotedge`
When I check the logs of the IoTCentralBridge module I get the following:
![iotcentral module error](https://user-images.githubusercontent.com/40599534/86543451-e69cf380-bf61-11ea-9e58-277740e637c1.PNG)
I then have to restart the IoTCentral module only and it works.
`sudo iotedge restart IoTCentralBridge`

Any idea as to why it does not connect the first time iotedge is restarted?

Kind Regards,

Yusuf

**Comment by emmanuel-bv** [comment]
@sseiber, any idea why it does not connect the first time iotedge is restarted?

**Comment by Y07yoyo** [comment]
The other issue is that when you go to `sudo iotedge list` it shows as the module is running even though it is logging **[log, [HealthService, info]] data: Health check interval** constantly. Because of this, it does not restart automatically and has to be manually restarted.

**Comment by sseiber** [comment]
I began seeing this with the latest version of Edge. I recently added some code that changed the health state of the module to critical when the client connection failed. This results in a module restart (after 3 critical health scans) which gets the module back into a running state. See the module.ts file in [this project](https://github.com/sseiber/lva-gateway) which uses the same pattern.

@Y07yoyo can you capture a support-bundle [see this article](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot) to help us diagnose?

@ebertrams we should get Venkat to take a look.

**Comment by Y07yoyo** [comment]
Hi @sseiber and @ebertrams,

I have restarted iotedge and then after a few minutes restarted the IoTCentralBridge Module. Attached is the support bundle for 1 hour.

I have taken a look at the project module.ts file, but I believe, in this project the restart module healthcheck failure is in the health.ts file?

I should create the restart function again in the module.ts file?

[support_bundle.zip](https://github.com/ebertrams/iotedge-iva-nano/files/4887374/support_bundle.zip)

**Comment by sseiber** [comment]
@Y07yoyo Thanks for the support bundle I'll send it along. Regarding the restart - I'll talk to @ebertrams to patch this project with the health-driven restart code.

**Comment by Y07yoyo** [comment]
@sseiber Thank you!

**Comment by emmanuel-bv** [comment]
PR fixing the health driven restart code now merged. Issue should be fixed.

**Comment by sseiber** [comment]
@ebertrams can you take another PR from my fork? I found and fixed the linting issues which were causing the Docker build to fail.

**Comment by emmanuel-bv** [comment]
Done! Thanks @sseiber !
