### ISSUE TITLE
Error building new docker

### ISSUE THREAD

**Issue by Y07yoyo** [ebertrams/iotedge-iva-nano#36]
Hi @ebertrams,

When trying to build the new Docker with the updated health checks, I get the following errors:

`src/apis/module.ts(32,31): error TS2345: Argument of type 'void' is not assignable to parameter of type 'string | object'.
src/manifest.ts(7,26): error TS6133: 'config' is declared but its value is never read.`

The build command returned a non-zero code: 2

Kind Regards,

Yusuf

**Comment by emmanuel-bv** [comment]
@sseiber , i merged your PR and @Y07yoyo  is seing this build command issue. Have you seen that before?

**Comment by emmanuel-bv** [comment]
@Y07yoyo just merged a new PR from sseiber which shoudl fix this issue. Thanks!
