### ISSUE TITLE
Cannot install moby-engine on Arm64 device

### ISSUE THREAD

**Issue by Y07yoyo** [ebertrams/iotedge-iva-nano#43]
Hi @ebertrams  and @sseiber,

I am trying to install IoT Edge on an arm64 device running nvidia jetpack 4.4, but I am getting errors when I try to install the moby-engine. 
It has something to do with having installed docker and nvidia-docker 2 already on the device. I require this to run deepstream.

The error is: 
```
ddi@ddi-nx:~$ sudo apt-get install moby-engine
[sudo] password for ddi: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 moby-engine : Depends: moby-containerd (>= 1.2) but it is not going to be installed
               Depends: moby-runc (>= 1.0.0~rc10) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I have followed the instructions provided here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux

Do you know how I can overcome this and get iotedge to work?

Kind Regards,

**Comment by sseiber** [comment]
@Y07yoyo - The Nvidia device already has the full Docker engine installed so when you are setting up IoT Edge just skip the step for installing the “engine”.

**Comment by emmanuel-bv** [comment]
@Y07yoyo yes you can use the default docker installation coming with jetpack 4.4. You dont need to install moby for that (which will only work with NVIDIA GPUs with the upcoming version of IoT Edge anyway). I d however recommend to stick to jetpack 4.3 for now sicne we will need to update the library to parse objects from custom vision models before that you can use it with jetpack 4.4.

**Comment by Y07yoyo** [comment]
Hi @sseiber and @ebertrams 
Thank you for this information.
