### ISSUE TITLE
Issues updating Device Properties

### ISSUE THREAD

**Issue by Y07yoyo** [ebertrams/iotedge-iva-nano#45]
Hi @ebertrams  and @sseiber ,

I am currently experiencing issues updating the device properties. I have tried three different ways and all three got errors.
1) Going to the Device Manage tab and updating the property:
![update property error](https://user-images.githubusercontent.com/40599534/95529009-8b2d4680-0a25-11eb-8a72-7f9747be89d3.PNG)
2) Creating a job in the IoT Central Application to update a property:
![failedJob](https://user-images.githubusercontent.com/40599534/95529031-9aac8f80-0a25-11eb-8b15-17af282bb38b.PNG)

3) Running a function app to send a PUT Request to update the property:
{
    "error": {
        "code": "InternalServerError",
        "message": "Something went wrong on our end. Please try again. You can contact support at https://aka.ms/iotcentral-support. Please include the following information. Request ID: ovtnqe, Time: Fri, 09 Oct 2020 00:08:44 GMT.",
        "requestId": "ovtnqe",
        "time": "Fri, 09 Oct 2020 00:08:44 GMT"
    }
}

All these three options were working normally for the past few days and months. Just having this issue today.

**Comment by emmanuel-bv** [comment]
Thanks for reporting @Y07yoyo. Looks like a temporary issue with IoT Central. @sseiber do you know if they are any outages/incidents ongoing?

**Comment by Y07yoyo** [comment]
Hi,

It seems as though now the device properties can be updated, however, when one property is updated, it resets the other properties if there is no message sent to it.
Also, I have noticed that different IoT Central Applications have had different behaviours for when properties are updated. For example I have attached the way the properties are updated for two different applications by looking at logs. 
![desiredpropsdelta1](https://user-images.githubusercontent.com/40599534/95642918-85a03100-0af7-11eb-961c-1a1ae5234f2f.PNG)
![desiredpropsdelta2](https://user-images.githubusercontent.com/40599534/95642922-889b2180-0af7-11eb-9299-863ee1bd5b7f.PNG)
Previously, everything was updated according to the first image, where the value could be extracted directly using this.detectionSetting.wpClubTotalCapacity. But now, I get a null value and cannot extract this data.

Another thing I noticed is that in one Application in Manage tab holds the previous values and only updates the new values, however in another app, it does not hold any previous value.
![values stored in this app](https://user-images.githubusercontent.com/40599534/95642978-e92a5e80-0af7-11eb-837a-412eaadf573e.PNG)
![Manage section value not stored](https://user-images.githubusercontent.com/40599534/95643014-15de7600-0af8-11eb-92c8-58c65d3a99b4.PNG)

Can you provide any insights into why this may be happening? 

Kind Regards,

Yusuf

**Comment by Y07yoyo** [comment]
I have managed to get the value using:
`const clubTotalCapacityValue = _get(this.detectionSettings.wpClubTotalCapacity, 'value');`
to get this to work at the moment. Just not sure why for some applications this is required but for others, just a straight const `const clubTotalCapacityValue = this.detectionSettings.wpClubTotalCapacity` is enough to get the value.

Also the issue still is that the values disappear from the manage tab when you save and go to another tab and then go back to the Manage tab.

Kind Regards,

Yusuf

**Comment by Y07yoyo** [comment]
In the code, I was able to set property values with the following code:
`this.detectionSetting.wpClubTotalCapacity = 2000;`

This is no longer possible. Is there an alternate way I can do this from the IoTCentralBridge code?

Kind Regards,

Yusuf

**Comment by Y07yoyo** [comment]
Issue is now fixed by Microsoft
