### ISSUE TITLE
Error with IoTCentralBridge connectivity

### ISSUE THREAD

**Issue by Y07yoyo** [ebertrams/iotedge-iva-nano#47]
Hi @ebertrams  and @sseiber,

I have just started a new IoTCentralApplication and when I go to IoTCentralBridge Logs I get the following:

`[2020-11-18T11:14:21+0000] ERROR        : [IoTCentralService,error] IoT Central connection error: mqtt.js returned Failure on first connection (Not authorized): getaddrinfo ENOTFOUND pm-cs-anly-svr01 error`

Can you shed some light into why this maybe happening? This causes the device to constantly restart but I was able to find the device.restart and comment it off for troubleshooting.

I have restart iotedge and the module a few times with no luck. 

IoTEdge Version: iotedge 1.0.10.2

Kind Regards,

Yusuf

**Comment by Y07yoyo** [comment]
I have tried to diagnose it but the device is provisioned and the ports are opened. Please see attached images
Below image shows the ports are opened
![networkports](https://user-images.githubusercontent.com/40599534/99611690-3b9c5a80-2a68-11eb-97c5-d342ec34c083.png)
below is running a diagnostic test and no data is being sent to iot central
![noData](https://user-images.githubusercontent.com/40599534/99611702-3e974b00-2a68-11eb-8d12-22fd3f5a6f02.JPG)
below shows the device provisioning status
![provisioned](https://user-images.githubusercontent.com/40599534/99611703-3f2fe180-2a68-11eb-910d-64168cd94d3a.JPG)
below is error from IoTCentralBridge logs
![logs](https://user-images.githubusercontent.com/40599534/99611704-3fc87800-2a68-11eb-841f-8009ad7499ff.JPG)

**Comment by sseiber** [comment]
@Y07yoyo Can you try restarting the Edge runtime with `sudo systemctl restart iotedge` and then try your scenario again. I want to rule out whether your developer self-signed certificates have become invalid.

Did you do any other editing on the config.yaml file other than the DPS registration section - e.g. hostname ?

**Comment by Y07yoyo** [comment]
Hi @sseiber 
Thank you for your response. After a day of troubleshooting, it appears the client IT Administrator has incorrectly named the PC in the host file. 
After spotting that mistake it now works!
Thank you again for your assistance.
