### ISSUE TITLE
Consider explaining what "jetcard" is used for 

### ISSUE THREAD

**Issue by kartben** [ebertrams/iotedge-iva-nano#7]
I think it would make sense to explain why the system needs to have jetcard installed, and what it adds to the stock Jetson Nano distro.

FWIW since the jetcard README says the below, and since we explicitly don't install PyTorch and tensorflow, it makes it hard to comprehend what/why we are installing. 
```
JetCard is a system configuration that makes it easy to get started with AI. It comes pre-loaded with

* A Jupyter Lab server that starts on boot for easy web programming
* A script to display the Jetson's IP address (and other stats)
* The popular deep learning frameworks PyTorch and TensorFlow
```

**Comment by emmanuel-bv** [comment]
I switched to using the DLI course from NVIDIA to avoid adding the JetCard concept. It added explanation on why we used this image instead of the JetPack one : this is just for the USB device mode, e.g. to work without an HDMI screen, separate keyboard and mouse.
